project_name: pwgen-go
before:
  hooks:
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version=v{{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{.CommitTimestamp}}"
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Others
      order: 999
brews:
  - homepage: https://github.com/gabe565/pwgen-go
    description: Command line password generator written in Go
    license: MIT
    repository:
      owner: gabe565
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      man1.install "manpages/{{ .ProjectName }}.1.gz"
      man1.install "manpages/{{ .ProjectName }}-template.1.gz"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/pwgen-go
    description: Command line password generator written in Go
    license: MIT
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/
        dst: /usr/share/man/man1
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.zsh
        dst:  /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
aurs:
  - name: "{{ .ProjectName }}-bin"
    homepage: https://github.com/gabe565/pwgen-go
    description: Command line password generator written in Go
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/LICENSE"
      # man pages
      install -Dm644 "./manpages/{{ .ProjectName }}.1.gz" "${pkgdir}/usr/share/man/man1/{{ .ProjectName }}.1.gz"
      install -Dm644 "./manpages/{{ .ProjectName }}-template.1.gz" "${pkgdir}/usr/share/man/man1/{{ .ProjectName }}.1.gz"
      # completions
      install -Dm644 "./completions/{{ .ProjectName }}.bash" "${pkgdir}/usr/share/bash-completion/completions/{{ .ProjectName }}"
      install -Dm644 "./completions/{{ .ProjectName }}.zsh" "${pkgdir}/usr/share/zsh/site-functions/_{{ .ProjectName }}"
      install -Dm644 "./completions/{{ .ProjectName }}.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
