# Number of passphrases to generate.
count = 10
# Default profile used to generate passphrases.
profile = 'diceware:4'
# Wordlist source. (one of: long, short1, short2, or a file path)
wordlist = 'long'
# Default template used to generate passphrases. If not empty, will override the default profile.
template = ''

# Preconfigured profiles and default parameters.
[profiles]
[profiles.alpha]
template = '{{ alpha . }}'
param = 32

[profiles.alphanum]
template = '{{ alphaNum . }}'
param = 32

[profiles.ascii]
template = '{{ ascii . }}'
param = 32

[profiles.bytes]
template = '{{ bytes . }}'
param = 32

[profiles.diceware]
template = '{{ wordsWithNum . | join "-" | title }}'
param = 4

[profiles.django]
template = '{{ randFromStr "abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)" 50 }}'

[profiles.laravel]
template = 'base64:{{ bytes 32 }}'

[profiles.pin]
template = '{{ num . }}'
param = 6

[profiles.words]
template = '{{ words . | join " " }}'
param = 4
