# Number of passphrases to generate.
count = 10
# Default profile used to generate passphrases.
profile = 'diceware:4'
# Wordlist to use. (one of: long, short1, short2)
wordlist = 'long'
# Default template used to generate passphrases. If not empty, will override the default profile.
template = ''

# Preconfigured profiles and default parameters.
[profiles]
[profiles.alpha]
template = '{{ randAlpha . }}'
param = 32

[profiles.ascii]
template = '{{ randAscii . }}'
param = 32

[profiles.diceware]
template = '{{ wordsWithNumber . | join "-" | title }}'
param = 4

[profiles.pin]
template = '{{ num . }}'
param = 6

[profiles.words]
template = '{{ words . | join " " }}'
param = 4
