package main

import (
	"bufio"
	"net/http"
	"strings"

	. "github.com/dave/jennifer/jen"
)

func main() {
	resp, err := http.Get("https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt")
	if err != nil {
		panic(err)
	}
	if resp.StatusCode != http.StatusOK {
		panic("invalid response: " + resp.Status)
	}
	defer resp.Body.Close()

	f := NewFile("wordlist")
	f.HeaderComment("// Code generated by internal/wordlist/generate; DO NOT EDIT.")

	f.Comment("EFF_Long is a wordlist intended for passphrases.")
	f.Comment("")
	f.Comment("Source: https://www.eff.org/dice")
	f.Var().Id("EFF_Long").Op("=").Id("Wordlist").BlockFunc(func(group *Group) {
		scanner := bufio.NewScanner(resp.Body)
		for scanner.Scan() {
			if scanner.Bytes()[0] != '#' {
				split := strings.Split(scanner.Text(), "\t")
				group.Lit(split[1]).Op(",")
			}
		}
	})

	if err := f.Save("eff_long.go"); err != nil {
		panic(err)
	}
}
